name: app_focus_club
description: "Mobile client app for Focus Club."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  cloud_firestore: ^6.3.0
  cloud_functions: ^6.2.0
  firebase_auth: ^6.4.0
  firebase_core: ^4.7.0
  firebase_storage: ^13.3.0
  flutter:
    sdk: flutter
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
